### ISSUE TITLE
sticky header problem - suggestion - request

### ISSUE THREAD

**Issue by homeza-freeart** [JoomShaper/helix-ultimate#149]
When scrolling the sticky header, disappearance and stuttering can be experienced. The problem is visible in the mobile view.
It’s okay to scroll down, but when you scroll up, the sticky header disappears and only comes up when I move the display. This is very confusing.
I suspect the problem is in main.js when switching the header to the stikcy header. add class and undo class.
Anyway, I don't understand why I need to switch back and forth to css? Why can't I keep the header fixed in my place? I think it would make sense. I made the following small changes to the code. Its professionalism may not be adequate, but it has temporarily solved the problem! This way, the sticky header is fixed in place. no disappearance, lagging problem:

-------------------------------------------------------------------

/ *** Device wise sticky header*
* @param {string} className the header className
* /

var deviceWiseStickyHeader = function (className, offsetTop) {
  if ($ ('body: not (.layout-edit-iframe)'). hasClass (className)) {
    var $ header = $ ('# sp-header');
    var headerHeight = $ header.outerHeight ();
    var $ stickyHeaderPlaceholder = $ ('. sticky-header-placeholder');

    var stickyHeader = function () {
    var scrollTop = $ (window) .scrollTop ();

         /* if (scrollTop> = offsetTop + 200) { */
              if (scrollTop> = offsetTop) {
                  $ header.addClass ('header-sticky');
                  $ stickyHeaderPlaceholder.height (headerHeight);
               } else {
                   if ($ header.hasClass ('header-sticky')) {
                   /* $header.removeClass('header-sticky ');
                       $ stickyHeaderPlaceholder.height ('inherit'); */
                       $ stickyHeaderPlaceholder.height (headerHeight);
                   }
               }
};
----------------------------------------------------------------
Is there a better and more professional solution to this?

**Comment by pavel-ww** [comment]
Hi. Yes I agree. The problem with sticky Header is still not solved. Using the animation along with offsetTop + 200 shifts the problem, but is not a solution

**Comment by yofiesetiawan** [comment]
From UX perspective, how about let it disappear on scroll down, but show when scroll up?

**Comment by pavel-ww** [comment]
> 
> 
> From UX perspective, how about let it disappear on scroll down, but show when scroll up?

This is a dubious opportunity, especially for mobile devices. I did that, but then gave up this solution. You can easily do it. www.w3schools.com/howto/howto_js_navbar_hide_scroll.asp

**Comment by mdamjadrana** [comment]
Header Sticky offset option added in backend and now default value is 0

**Comment by pavel-ww** [comment]
Hi @mdamjadrana. Header is almost good, but not perfect. It is still needs an animation disable button. When the offset is 0, there is no point in the animation.

There is also another small problem (in Header Style 1). When the Header switches to Sticky, TopBar is flicker under Header. This problem is caused by the fact that the call of Sticky-Header-Placeholder is located in the wrong place. It should always be before Header. Now it's before Top-Bar.

It should be here.
![2](https://user-images.githubusercontent.com/67497496/126030789-0a9f8425-549a-41ac-b295-0df4a57278e3.jpg)

**Comment by joomleb** [comment]
Please, Was this fixed with the 2.0.2 release?

**Comment by FabienCCFR** [comment]
> Please, Was this fixed with the 2.0.2 release?

Hi ! It seems not :-(

**Comment by homeza-freeart** [comment]
Unfortunately, the sticky header is still not good.
It swims unnecessarily on the phone when I scroll the page.
When scrolling down, it's still good, then when you scroll up, it disappears, and when I scroll down again, it comes back flashing, shaking.
This is very confusing!
Its operation is completely uncertain. :(

**Comment by panta7** [comment]
Same problem here.

**Comment by elmarra90** [comment]
Hi, I also found myself in the same problem.
I have tried this buffer solution which seems to temporarily solve the problems.
It is currently the only solution that seems to be solving, hoping that the developers will fix the problem soon
Obviously always working on the file "main.js" and adding the css code:

css:

#sp-header { animation: none !important;}
#sp-header.header-sticky {  position: fixed !important;}

edit to the js file:
`
jQuery(function ($) {

    // Stikcy Header
    if ($('body').hasClass('sticky-header')) {
        var header = $('#sp-header');

        if($('#sp-header').length) {
            var headerHeight = header.outerHeight();
            var stickyHeaderTop = header.offset().top;
            var stickyHeader = function () {
                var scrollTop = $(window).scrollTop();
                if (scrollTop > stickyHeaderTop) {
                    header.addClass('header-sticky');
                } else {
                    if (header.hasClass('header-sticky')) {
                        header.removeClass('header-sticky');
                    }
                }
            };
            stickyHeader();
            $(window).scroll(function () {
                stickyHeader();
            });
        }

        if ($('body').hasClass('layout-boxed')) {
            var windowWidth = header.parent().outerWidth();
            header.css({"max-width": windowWidth, "left": "auto"});
        }
    }

	;`

**Comment by joomlaphp** [comment]
This issue persists in the new version. Can it be fixed in the next version?

**Comment by mdamjadrana** [comment]
Issue solved [check this](https://github.com/JoomShaper/helix-ultimate/commit/c2ab2e9a7d33ceef9931a169f62dfacda23fb016)
