### ISSUE TITLE
Can't Load Featured Image In Blog Options Tab Of An Article

### ISSUE THREAD

**Issue by oDELORON** [JoomShaper/helix-ultimate#247]
### Steps to reproduce the issue

1. creating an article
2. going to Blog Options Tab
3. try to upload a Featured Image

### Expected result

Getting the uploaded image as 'featured' in the field, and the image displaying in the site in frontend (via the Article Addon of SPPB)

### Actual result

Nothing happens but the bar scrolling very quickly and no image at all is selected/displayed...

### System information (as much as possible)

Joomla 3.10.3
Helix Ultimate Framework 2.0.5
SP Page Builder Pro 3.8.0

### Additional comments

The action is going well (successful upload) with an older version of Helix Ultimate (e.g. 1.1.4)

**Comment by webwichtl** [comment]
I tried using the older version of Helix 1.1.4, but it still doesn't work.

**Comment by matrix630307** [comment]
does anyone have a manual solution until this bug is fixed?
it is very important for me.
thank you

**Comment by oDELORON** [comment]
I'm sorry but the only way to get through it that I found for now is actually to uninstall the HU Framework 2.0.5, then setup HU 1.1.4, then create my article and upload the Featured Image, then uninstall HU 1.1.4, then re-install HU 2.0.5... This process is really very restrictive as you guess but to me it was successfull.

**Comment by mdamjadrana** [comment]
I tested it works fine. can you share a video please.

**Comment by oDELORON** [comment]
> I tested it works fine. can you share a video please.

Sorry for the delay, here is a video capture of an attempt to upload a picture in the Blog options tab :
https://user-images.githubusercontent.com/94623075/185884360-19a4e3e4-4490-4ef1-a1bc-5d805d8a75aa.mp4

Well the issue is not closed for my concern, and nobody gave me any beggining of a clue of what could be done...

**Comment by mi-prakash** [comment]
@oDELORON This issue has been fixed. Please use latest version of helix ultimate and latest joomla version
closing the issue

**Comment by oDELORON** [comment]
Hi @mi-prakash, sorry but the issue is not fixed... I use latest version of Joomla 3 (3.10.11) and of Helix Ultimate (2.0.11) and th problem still remains.

**Comment by mi-prakash** [comment]
@oDELORON 
 I think this issue occurs when the blog is created by a user in past which is not exists now. can u please delete the blog data and create a new blog copying the content and try again?
 I think this will solve your issue. I'm re-opening the issue and waiting for your feedback

**Comment by oDELORON** [comment]
@mi-prakash 
It is not about a "created blog", it simply occurs when creating an article and trying to upload a Featured Image (in the "Blog Options" tab of the article).
And there is no new user, I am still the only who is accessing this site...

**Comment by mi-prakash** [comment]
@oDELORON 
ara u using the Quict Start package?

**Comment by mi-prakash** [comment]
@oDELORON 
We need to check your source code. Please create an issue on our forum. You can get direct communication there and they can assist you quickly.
https://www.joomshaper.com/forum

**Comment by oDELORON** [comment]
Hi guys,
Well yes, is has been solved at this time.
The solution was to be found in the php parameters of the site:
_In Joomla admin check: System Information > PHP Information > and search "memory_limit" - what is a value that you have? 
If you have "-1" (no-limit) please go to hosting cPanel or ask hosting support to change this value. 
We recommend using any value above 256M. For a typical small or middle website: 512M should be OK. 
Save changes and see if your value was updated. 
Then the image will be available to be downloaded!_
Whatever, I think the issue is now natively solved with Helix Ultimate 2.1
Thanks for your follow-up.

**Comment by mi-prakash** [comment]
@oDELORON  
Thanks for your feed back
If everything is ok then you can close the issue.
Thank you
