### ISSUE TITLE
Offcanvas appended below the header - BUG

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#72]
Hi guys, 
PHP 7.3.19 + Joomla 3.9.19 + Helix Ultimate 2.0 alpha - [url=https://photos.app.goo.gl/NbxFhWt3o3hboMuT6]I attach an image[/url] as example - [url=https://test2.egulp.net/]here the test site[/url]

[b]BUG[/b]: the Offcanvas is appended below the Header instead to be appended over it

Please, Can you replicate it ?

**Comment by ahamed** [comment]
Thank you for your valuable response. The issue is fixed.

**Comment by joomleb** [comment]
Thanks Ahamed!

**Comment by joomleb** [comment]
Hi, 
you closed the ticket, but on Alpha 2 the BUG is still there...

**Comment by joomleb** [comment]
This ticket has been closed, but on Alpha 6 the BUG is still there.
I described it again on this new ticket https://github.com/JoomShaper/helix-ultimate/issues/111  point 3B and it seems to be related with the activation of the "Sticky Header" feature...

**Comment by ahamed** [comment]
@joomleb
On Alpha 6 the OffCanvas appears like-
![image](https://user-images.githubusercontent.com/5783354/109266669-892c1e80-7832-11eb-85b8-8ac8f45e5f0d.png)

If it is not like that then please clear the cache and hard reload your browser.

**Comment by mdamjadrana** [comment]
It's not an issue. if your offcanvas position is right you can easily drag helix settings area  from left to right or any position. We priority helix settings visibility over offcanvas visibility.
